server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: productModule
          uri: http://localhost:9091
          predicates:
            - Path=/product/**
        - id: cartModule
          uri: http://localhost:9092
          predicates:
            - Path=/cart/**
            
            
    discovery:
      enabled: true
  application:
     name: api-gateway

